name: result_flow_dio
description: Adapts Dio HTTP responses and errors to the result_flow Result type.
version: 1.0.0
repository: https://github.com/nayefradwi/result_flow_dio

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  result_flow: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^7.0.0

